package fr.kissy;

import fr.kissy.model.City;
import net.htmlparser.jericho.Element;
import net.htmlparser.jericho.HTMLElementName;
import net.htmlparser.jericho.Source;

import java.io.*;
import java.net.URL;
import java.nio.file.Paths;
import java.util.List;
import java.util.Properties;

/**
 * Created by guillaume on 06/08/2017.
 */
public class FetchQuandPartirData {
    public static void main(String[] args) throws IOException, InterruptedException {
        final String dataFileName = "city-data.properties";

        Properties data = new Properties();
        if (Paths.get(dataFileName).toFile().exists()) {
            try (InputStream is = new FileInputStream(dataFileName)) {
                data.load(is);
            }
        }

        // 224 pays
        for (int id = 1; id <= 224; id++) {
            if (countryAlreadyFetched(data, id)) {
                continue;
            }

            parseCountryData(data, id);
            Thread.sleep(100);
        }

        try (OutputStream os = new FileOutputStream(dataFileName)) {
            data.store(os, "Generated by travel-heatmap");
        }
    }

    private static boolean countryAlreadyFetched(Properties data, int id) {
        for (Object cityId : data.keySet()) {
            if (((String) cityId).startsWith(id + "-")) {
                return true;
            }
        }

        return false;
    }

    private static void parseCountryData(Properties data, int id) throws IOException {
        try {
            System.out.println("Fetching data for country id " + id);
            String sourceUrlString = "http://www.quandpartir.com/meteo/afrique-du-sud-idpaysglobal-" + id + ".html";
            Source source = new Source(new URL(sourceUrlString));

            List<Element> headers = source.getAllElements(HTMLElementName.H1);
            String title = headers.get(0).getTextExtractor().toString();
            String country = title.substring(0, title.indexOf(" : "));


            Element citiesTable = source.getElementById("tablevilles");
            List<Element> cities = citiesTable.getAllElements(HTMLElementName.TR);
            for (Element city : cities) {
                if (city.getAttributeValue("class") != null) {
                    continue;
                }

                List<Element> months = city.getAllElements(HTMLElementName.TD);
                String cityTitle = months.get(0).getTextExtractor().toString();
                City cityData = new City(country, cityTitle);

                for (int i = 1; i <= 12; i++) {
                    Element month = months.get(i);
                    String cityScore = month.getAttributeValue("class").replace("note_ville_", "");
                    cityData.getScore()[i - 1] = Integer.parseInt(cityScore, 10);
                }

                data.put(id + "-" + cityTitle.replace(" ", "_"), cityData.toPropertyString());
            }
        } catch (Exception e) {
            System.out.println("Error while fetching country " + id);
            e.printStackTrace();
        }
    }
}
